# TODO(fgorczynski): Change to multistage build
FROM python:3.13-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
COPY requirements*.txt .
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
COPY . .
RUN mkdir -p uploads data
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
